<?php
/**
 * Enqueues theme assets
 *
 * Note: Do NOT edit this file to add assets. Do that in the `inc/assets-config.php` file.
 *
 * @package CassidyWP\StarterBlockTheme\Functions
 * @version 1.0.0
 */

declare( strict_types = 1 );
namespace CassidyWP\StarterBlockTheme;

/**
 * Enqueue theme styles and scripts
 */
if ( ! function_exists( 'CassidyWP\StarterBlockTheme\enqueue_theme_assets' ) ) :
	/**
	 * Enqueue theme assets
	 *
	 * @since 1.0.0
	 * @return void
	 */
	function enqueue_theme_assets(): void {
		// Retrieve assets properties.
		$theme_styles  = get_theme_assets_config( 'styles' );
		$theme_scripts = get_theme_assets_config( 'scripts' );

		// Enqueue theme stylesheets.
		foreach ( $theme_styles as $style => $properties ) {
			wp_enqueue_style( $properties['handle'] );
		}

		// Enqueue theme scripts.
		foreach ( $theme_scripts as $script => $properties ) {
			wp_enqueue_script( $properties['handle'] );
		}
	}
endif;

add_action( 'wp_enqueue_scripts', 'CassidyWP\StarterBlockTheme\enqueue_theme_assets' );

/**
 * Enqueue editor UI assets
 */
if ( ! function_exists( 'CassidyWP\StarterBlockTheme\enqueue_editor_ui_assets' ) ) :
	/**
	 * Enqueue assets for the Editor UI
	 *
	 * @since 1.0.0
	 * @return void
	 */
	function enqueue_editor_ui_assets(): void {
		// Retrieve assets properties.
		$editor_ui_styles  = get_theme_assets_config( 'editor_ui_styles' );
		$editor_ui_scripts = get_theme_assets_config( 'editor_ui_scripts' );

		// Enqueue Editor UI stylesheets.
		foreach ( $editor_ui_styles as $editor_ui_style => $properties ) {
			wp_enqueue_style( $properties['handle'] );
		}

		// Enqueue Editor UI scripts.
		foreach ( $editor_ui_scripts as $editor_ui_script => $properties ) {
			wp_enqueue_script( $properties['handle'] );
		}
	}
endif;

add_action( 'enqueue_block_editor_assets', 'CassidyWP\StarterBlockTheme\enqueue_editor_ui_assets' );

/**
 * Enqueue editor iframe content stylesheets
 */
if ( ! function_exists( 'CassidyWP\StarterBlockTheme\enqueue_editor_styles' ) ) :
	/**
	 * Enqueue editor content stylesheets
	 *
	 * @since 1.0.0
	 * @return void
	 */
	function enqueue_editor_styles(): void {
		$editor_styles = get_editor_styles_config();

		foreach ( $editor_styles as $editor_style => $properties ) {
			add_editor_style( $properties['path'] );
		}
	}
endif;

add_action( 'after_setup_theme', 'CassidyWP\StarterBlockTheme\enqueue_editor_styles' );

/**
 * Enqueue individual block stylesheets
 */
if ( ! function_exists( 'CassidyWP\StarterBlockTheme\enqueue_block_styles' ) ) :
	/**
	 * Enqueue individual block stylesheets
	 *
	 * @since 1.0.0
	 * @link https://developer.wordpress.org/reference/functions/wp_enqueue_block_style/
	 * @return void
	 */
	function enqueue_block_styles(): void {
		$block_styles = get_block_styles_config();

		foreach ( $block_styles as $block_style => $properties ) {
			$block_name = $properties['name'];
			$block_args = $properties['args'];

			wp_enqueue_block_style( $block_name, $block_args );
		}
	}
endif;

add_action( 'after_setup_theme', 'CassidyWP\StarterBlockTheme\enqueue_block_styles' );
